---
# Source: generic-ioc/templates/ioc.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name:  generic-ioc
  labels:
    app: generic-ioc
    beamline: bl45p
    ioc_version: "2023.10.1+b2"
    is_ioc: "True"
data:
---
# Source: generic-ioc/templates/ioc.yaml
# Create a new config map for every Deployment that containes the files
# found in config folder
apiVersion: v1
kind: ConfigMap
metadata:
  name: special-config
data:
---
# Source: generic-ioc/templates/ioc.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: generic-ioc
  labels:
    app: generic-ioc
    beamline: bl45p
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
---
# Source: generic-ioc/templates/ioc.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: generic-ioc
  labels:
    app: generic-ioc
    beamline: bl45p
    ioc_version: "2023.10.1+b2"
    is_ioc: "True"
  annotations:
    kubernetes.io/change-cause: 2023.10.1+b2 deployed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: generic-ioc
  template:
    metadata:
      labels:
        app: generic-ioc
        beamline: bl45p
        ioc_version: "2023.10.1+b2"
        is_ioc: "True"
    spec:
      
      hostNetwork: true
      terminationGracePeriodSeconds: 15 # nice to have quick restarts on IOCs
      volumes:
        - name: generic-ioc
          persistentVolumeClaim:
            claimName: generic-ioc
        - name: config-volume
          configMap:
            name: generic-ioc
      containers:
      - name: generic-ioc
        image: ghcr.io/epics-containers/ioc-template-linux-runtime:23.9.1
        command:
          - bash
        args:
          - /epics/ioc/start.sh
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - /epics/ioc/liveness.sh
          initialDelaySeconds: 120
          periodSeconds: 10
        lifecycle:
          preStop:
            exec:
              command: ["bash", "-c", "/epics/ioc/stop.sh"]
        volumeMounts:
        - name: config-volume
          mountPath: /epics/ioc/config
        - name: generic-ioc
          mountPath: /autosave
        stdin: true
        tty: true
        securityContext:
          allowPrivilegeEscalation: false
        resources:
          limits:
            cpu: "3"
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 200Mi
        imagePullPolicy: Always
        env:
        - name: IOCSH_PS1
          value: "generic-ioc > "
        - name: IOC_NAME
          value: generic-ioc
        - name: IOC_PREFIX
          value: "generic-ioc"
        - name: IOC_VERSION
          value: "2023.10.1+b2"
        - name: K8S_IOC_TFTP_ADDR
          value: "172.23.168.220"
        - name: K8S_IOC_TFTP_PORT
          value: "69"
        - name: K8S_IOC_NFS_MOUNT
          value: "172.23.168.220:iocs"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beamline
                operator: In
                values:
                  - bl45p
      tolerations:
        - key: nodetype
          operator: Equal
          value: bl45p
          effect: NoSchedule
