
# stream port for Gige Vision
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-stream
  namespace: {{ .Release.Namespace }}
  annotations:
    metallb.universe.tf/allow-shared-ip: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    beamline: {{ .Values.beamline }}
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: ca-udp
      port: 53000
      targetPort: 53000
      protocol: UDP
  selector:
    app: {{ .Chart.Name }}

