stages:
  - build
build_image:
  stage: build
  tags:
    - docker-image
  image:
    name: gcr.io/diamond-pubreg/buildutil:0.0.0
    entrypoint: ["/bin/sh", "-c"]
  script:
    - env | grep "CI_"
    - ./.helm-ci.sh
  only:
    refs:
      - master