stages:
  - helm_push

build:
  tags:
    - argus
    - docker-image
  stage: helm_push
  variables:
    REGISTRY_ROOT: helm-test.diamond.ac.uk/
    CR_TOKEN: $NEXUS_USER
    CR_USER: $NEXUS_PASSWORD
  image:
    name: alpine/k8s
    entrypoint: [""]
  script:
    - ./tar_config_src.sh
    - if [ "${CI_COMMIT_TAG}" != "" ] ; then
      export DO_PUSH=true
      export TAG=${GITHUB_REF_NAME}
      fi
    - for ioc_root in $(ls -d iocs/*/) ; do
      ./helm-push.sh ${ioc_root}
      done
