stages:
  - helm_push

build:
  tags:
    - argus
    - docker-image
  stage: helm_push
  variables:
    REGISTRY_ROOT: helm-test.diamond.ac.uk/iocs
    REGISTRY_FOLDER: $CI_PROJECT_NAME
    CR_TOKEN: $NEXUS_PASSWORD
    CR_USER: $NEXUS_USER
  image:
    name: alpine/k8s:1.25.6
    entrypoint: [""]
  script:
    # the included busybox diff does not support --exclude
    - apk --no-cache add diffutils
    # tar up the ioc source if needed
    - ./tar_config_src.sh
    # only push if this is a tagged build
    - if [ "${CI_COMMIT_TAG}" != "" ] ; then
      export DO_PUSH=true ;
      export TAG=${CI_COMMIT_TAG} ;
      fi
    # build and push the helm chart for each ioc
    - for ioc_root in $(ls -d iocs/*/) ; do
      ./helm-push.sh ${ioc_root} ;
      done
