stages:
  - helm_push
build:
  tags:
    - argus
    - docker-image
  stage: helm_push

  variables:
    REGISTRY_ROOT: helm-test.diamond.ac.uk/iocs
    REGISTRY_FOLDER: $CI_PROJECT_NAME
    CR_TOKEN: $NEXUS_PASSWORD
    CR_USER: $NEXUS_USER
    TAG: ${CI_COMMIT_TAG}

  image:
    name: alpine/k8s:1.25.6
    entrypoint: [""]

  script:
    - sh ./ci_build.sh
