apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bl45p
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: bl45p
  destination:
    server: https://api.argus.diamond.ac.uk:6443
    namespace: bl45p
  source:
    path: apps
    repoURL: https://github.com/epics-containers/bl45p.git
    targetRevision: main
    helm:
      version: v3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  # syncOptions:
  #   # only update apps whose app manifest has changed?
  #   - ApplyOutOfSyncOnly=true
  #   - Replace=true
  #   - Force=true
