{{- $currentScope := .}}
{{- range .Values.services -}}
{{- if ne .enabled false -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .service }}
  namespace: {{ $currentScope.Release.Namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ default $currentScope.Release.Namespace $currentScope.Values.project }}
  destination:
    namespace: {{ $currentScope.Values.destination.namespace }}
    name: {{ $currentScope.Values.destination.name }}
  source:
    path: services/{{ .service }}
    repoURL: {{ default $currentScope.Values.source.repoURL .repoURL }}
    targetRevision: {{ default $currentScope.Values.source.targetRevision .targetRevision }}
    helm:
      version: v3
      valueFiles:
        - ../beamline_values.yaml
        - values.yaml
      # this passes the enabled flag down to the ioc-instance chart but we
      # don't need this as we don't create disabled apps - keeping it as an
      # example of how to do this for future features.
      values: |
        ioc-instance:
          enabled: {{ ternary true false (ne .enabled false) }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      # don't restart pods unless there has been a change
      - ApplyOutOfSyncOnly=true
      # - Replace=true
      # - Force=true
---
{{- end -}}
{{- end -}}