{{- $currentScope := .}}
{{- range .Values.services -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .service }}
  namespace: {{ $currentScope.Release.Namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ default $currentScope.Release.Namespace $currentScope.Values.project }}
  destination:
    namespace: {{ $currentScope.Values.destination.namespace }}
    name: {{ $currentScope.Values.destination.name }}
  source:
    path: {{ default (print "services/" .service) .chart }}
    repoURL: {{ default $currentScope.Values.source.repoURL .repoURL }}
    targetRevision: {{ default $currentScope.Values.source.targetRevision .targetRevision }}
    helm:
      parameters:
        name: ioc-instance.enabled
        value: {{ ternary true false (ne .enabled false) }}
        {{-  range $k, $v := .values }}
        name: {{ $k }}
        value: {{ $v }}
        {{- end }}
      version: v3
      valueFiles:
        - ../beamline_values.yaml
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      # don't restart pods unless there has been a change
      - ApplyOutOfSyncOnly=true
---
{{- end -}}