{{ $currentScope := .}}
{{- range .Values.services }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .service }}
  namespace: {{ $currentScope.Release.Namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ default $currentScope.Release.Namespace $currentScope.Values.project }}
  destination:
    namespace: {{ $currentScope.Values.destination.namespace }}
    name: {{ $currentScope.Values.destination.name }}
  source:
    path: services/{{ .service }}
    repoURL: {{ default $currentScope.Values.source.repoURL .repoURL }}
    targetRevision: {{ default $currentScope.Values.source.targetRevision .targetRevision }}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Replace=true
---

{{- end }}