# yaml-language-server: $schema=../../../../ioc-adaravis/ibek-defs/_global/all.ibek.support.schema.json
ioc_name: bl45p-ea-ioc-01
description: sample camera IOC for BL45P
generic_ioc_image: ghcr.io/epics-containers/ioc-adaravis-linux-runtime:23.5.1

entities:
  - type: epics.EpicsCaMaxArrayBytes
    max_bytes: 6000000

  - type: ADAravis.ADAravis
    PORT: DET.DET
    P: BL45P-EA-MAP-01
    R: ":DET:"
    ID: 172.23.59.11

  - type: ADAravis.MantaG235B
    camera: DET.DET

  - type: ADAravis.ADAravis
    PORT: DIFF.DET
    P: BL45P-EA-DIFF-01
    R: ":DET:"
    ID: 172.23.59.12

  - type: ADAravis.Mako_G234B
    camera: DIFF.DET
