base_image: ghcr.io/epics-containers/ioc-template-rtems-runtime:23.3.3b6

# for RTEMS IOCS add the volume name for the filesystem where RTEMS
# IOCs look for their files
nfsv2TftpClaim: ioc-nfsv2-tftp-claim

env:
  # Liveness configuration
  - name: K8S_IOC_LIVENESS_ENABLED
    value: true
    # leave address blank unless PV is not normally discoverable
  - name: K8S_IOC_ADDRESS
    value: 172.23.250.15
    # TODO also should have default value for port
  - name: K8S_IOC_PORT
    value: 7064
  - name: K8S_IOC_PV
    value: bl45p-ea-ioc-90:UPTIME

  # RTEMS console connection details
  - name: RTEMS_VME_CONSOLE_ADDR
    value: ts0001.cs.diamond.ac.uk
  - name: RTEMS_VME_CONSOLE_PORT
    value: "7007"
  - name: "RTEMS_VME_AUTO_REBOOT"
    value: true
  - name: "RTEMS_VME_AUTO_PAUSE"
    value: true

  # RTEMS crate monitor connection details
  - name: RTEMS_VME_CRATE_MONITOR_ADDR
    value: ts0001.cs.diamond.ac.uk
  - name: "RTEMS_VME_CRATE_MONITOR_PORT"
    value: "7008"
