# yaml-language-server: $schema=https://github.com/marcelldls/ec-helm-charts/releases/download/3.4.4/ioc-instance.schema.json#/$defs/service

# latest container image for GigE cameras from the GitHub Container Registry
ioc-instance:
  beamline: bl45p

  image: ghcr.io/epics-containers/ioc-adaravis-runtime:2024.6.2

  securityContext:
    runAsUser: 37988
    runAsGroup: 37988

  dataVolume:
    pvc: false
    hostPath: /dls/p45/data

  useAffinity: true

  # extra toleration for bl45p's nodetype taint (benign change)
  tolerations:
    - key: "nodetype"
      operator: "Equal"
      value: "test-rig"
      effect: "NoSchedule"
