# default values for all IOCs on bl45p
exports:
  beamline_defaults:
    beamline: bl45p
    namespace: bl45p
    serviceAccount: bl45p-priv

    # provide a PVC for autosave
    autosave: true

    hostNetwork: true

    # useAffinity - only run on nodes with label beamline:bl45p
    useAffinity: true

    # some beamline default resource limits
    resources:
      limits:
        cpu: "3"
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 200Mi

    # Where to find RTEMS IOC files
    globalenv:
      - name: "K8S_IOC_TFTP_ADDR"
        value: "172.23.168.220"
      - name: "K8S_IOC_TFTP_PORT"
        value: "69"
      - name: "K8S_IOC_NFS_MOUNT"
        value: ""
