# yaml-language-server: $schema=https://github.com/marcelldls/ec-helm-charts/releases/download/3.4.4/ioc-instance.schema.json#/$defs/service

# This command will list the overridable values and their defaults:
#   helm show values oci://ghcr.io/epics-containers/ioc-instance

ioc-instance:
  beamline: bl45p

  image:

  securityContext:
    runAsUser: 37988
    runAsGroup: 37988

  dataVolume:
    pvc: false
    hostPath: /dls/p45/data

  useAffinity: true

  # extra toleration for bl45p's nodetype taint
  tolerations:
    - key: "nodetype"
      operator: "Equal"
      value: "test-rig"
      effect: "NoSchedule"
