apiVersion: v2
name: bl45p-ea-ioc-01
description: |
    Gige camera IOC for BL45P

type: application

# chart and app version - these are updated automatically by CI
version: 2021.04.29-1440
appVersion: 2021.04.29-1440

dependencies:
  - name: ioc-chart
    version: 0.2.2
    repository: "oci://europe-docker.pkg.dev/diamond-privreg/controls/"
