name: bl45p-ea-ioc-01
base_image: ghcr.io/epics-containers/ioc-adaravis:2.2.1r3.0.run

# Area detector may need more than beamline default resources
resources:
  limits:
    cpu: 4
    memory: 4Gi
  requests:
    cpu: 1
    memory: 500Mi