beamline: bl45p
namespace: epics-iocs
base_image: ghcr.io/epics-containers/ioc-adaravis:2.2.1r3.0.run

# root folder of generic ioc source - not expected to change
iocFolder: /epics/ioc

# useAffinity - only run on nodes with label beamline:bl45p
useAffinity: true
# resource limits
memory: 2048Mi
cpu: 4

# when autosave is true: create PVC and mount at /autosave
autosave: true
