# yaml-language-server: $schema=https://github.com/marcelldls/ec-helm-charts/releases/download/3.4.4/ioc-instance.schema.json#/$defs/service

# latest container image for GigE cameras from the GitHub Container Registry
ioc-instance:
  beamline: bl45p

  image: ghcr.io/pandablocks/pandablocks-ioc:0.7.1

  # this causes our config folder's start.sh to be mounted over the default
  # /epics/ioc/start.sh - thus making the pandaBlocks container image have
  # the same entrypoint as ioc-template based images
  iocConfig: /epics/ioc

  securityContext:
    runAsUser: 37988
    runAsGroup: 37988

  dataVolume:
    pvc: false
    hostPath: /dls/p45/data

  useAffinity: true

  # extra toleration for bl45p's nodetype taint
  tolerations:
    - key: "nodetype"
      operator: "Equal"
      value: "test-rig"
      effect: "NoSchedule"
