# yaml-language-server: $schema=https://github.com/marcelldls/ec-helm-charts/releases/download/3.4.4/ioc-instance.schema.json#/$defs/service

# latest container image for GigE cameras from the GitHub Container Registry
ioc-instance:
  image: ghcr.io/epics-containers/ioc-pmac-runtime:2024.3.2b2

  dataVolume:
    # don't create a pvc - instead we will mount a host folder
    pvc: true
    # A path on the host machine to write data into. Also used as the path where
    # the folder will be mounted inside of the container so that users need not
    # be confused about inside/outside container paths.
    hostPath: /data

  # the beamline name - only set for beamlines
  beamline: bl45p
  # the name of the repository in which the IOC is grouped
  ioc_group: bl45p
  # the location where the IOCs will run - same as beamline for beamlines
  location: bl45p

  # typically use the default service account in the namespace.
  # If you need to specify an alternative then uncomment below
  # serviceAccountName: k8s-p38-iocs

  # useHostNetwork - use host network for IOC - required for Channel Access
  # to work outside of the cluster
  hostNetwork: true

  # useAffinity - only run on nodes with label beamline:<beamline-name>
  # or location:<location-name>
  # Comment out useAffiniity for dedicated cluster, set to true for shared cluster

  useAffinity: true

  # root folder for ioc source/binaries inside generic IOC container
  iocFolder: /epics/ioc
  iocConfig: /epics/ioc/config
  # scripts for controlling the IOC
  startCommand: /epics/ioc/start.sh
  stop: /epics/ioc/stop.sh
  liveness: /epics/ioc/liveness.sh

  # The following are added to the pod's environment and are shared by all
  # IOCs. TODO - these defaults are for a lab crate in DLS - if you have
  # RTEMS IOCs update accordingly.
  globalEnv:
    # These variables are used by RTEMS IOCs to find the NFS and TFTP servers
    - name: "RTEMS_ROOT_NFS"
      value: "/nfsv2-tftp"
    - name: "RTEMS_ROOT_TFTP"
      value: "/nfsv2-tftp"
    - name: "RTEMS_NFS_IP"
      value: "172.23.90.238"
    - name: "RTEMS_TFTP_IP"
      value: "172.23.90.238"
    # NB. Gateway and Netmask are the same for all RTEMS IOCs on a beamline
    # But may need to move these to iocEnv for Machine IOCs?
    - name: "RTEMS_IOC_NETMASK"
      value: "255.255.240.0"
    - name: "RTEMS_IOC_GATEWAY"
      value: "172.23.240.254"
  # This also adds environment variables to the pod, but this should be
  # overridden by each IOC's values.yaml as needed. Don't set values in this
  # file because they will be overridden by IOCs.
  # iocEnv:
  #   - name: ""
  #     value: ""

  # use the shared PVC for publishing opi files over http (see services/opis)
  opisClaim: bl45p-opi-claim
  # use the shared PVC for publishing opi files over http (see services/opis)
  runtimeClaim: bl45p-runtime-claim
  # use the shared PVC autosave files (comment out for no autosave)
  autosaveClaim: bl45p-autosave-claim

  # default resource limits
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 64M

  # extra tolerations as required
  tolerations:
    - key: "nodetype"
      operator: "Equal"
      value: "test-rig"
      effect: "NoSchedule"
