# yaml-language-server: $schema=https://github.com/marcelldls/ec-helm-charts/releases/download/3.4.4/ioc-instance.schema.json#/$defs/service

# latest container image for GigE cameras from the GitHub Container Registry
ioc-instance:
  beamline: bl45p

  image: ghcr.io/epics-containers/ioc-pmac-runtime:2024.3.2b2

  useAffinity: true

  # extra toleration for bl45p's nodetype taint
  tolerations:
    - key: "nodetype"
      operator: "Equal"
      value: "test-rig"
      effect: "NoSchedule"
# benign change

