apiVersion: v2
name: generic-ioc
description: |
  Generic IOC Helm Chart for epics-containers

type: application

# chart and version
version: 1.0.0

dependencies:
  - name: beamline-chart
    version: "1.0.0"
    repository: file://../../beamline-chart
    import-values:
      - beamline_defaults
  - name: helm-ioc-lib
    version: "2.0.0"
    repository: oci://ghcr.io/epics-containers
    import-values:
      - defaults
