beamline: bl45p
namespace: epics-iocs
base_image: ghcr.io/epics-containers/ioc-pmac-linux-runtime:23.3.4

# root folder of generic ioc source - not expected to change
iocFolder: /epics/ioc

# useAffinity - only run on nodes with label beamline:bl45p
useAffinity: true
# use default resource limits
memory:
cpu:

# when autosave is true: create PVC and mount at /autosave
autosave: true
