project: bl45p
destination:
  name: pollux
  namespace: bl45p
source:
  repoURL: https://github.com/epics-containers/bl45p.git
  targetRevision: main

# list of services to deploy from the /services folder of this repo
# each item is of the form:
# - service: service folder (name of service is the folder name)
#   enabled: set to false to turn off an IOC
#   targetRevision: optional override for targetRevision above
#   repoURL: optional override for repoURL above

services:
  # shared epics services ######################################################
  - service: epics-pvcs
  - service: epics-opis

  # daq services ###############################################################
  - service: daq-rabbitmq
  # commented out because daq-blueapi does not obey ioc-instance.enabled
  # TODO: move enabled to global and set up our helm charts to obey that as
  # they see fit.
  # - service: daq-blueapi
  #   enabled: false # --- boot looping

  # epics iocs #################################################################

  # TODO dls-aravis will be a published chart and we will change the schema here
  # so that you still get to name your service as well as pass the chart URI.
  # For this demo dls-aravis is a local chart in the services folder.
  - service: dls-aravis
    enabled: false # --- camera is offline
    values:
      P: BL45P-EA-MAP-01
      ID: bl45p-ea-detector-01
  - service: dls-aravis
    values:
      P: BL45P-EA-DIFF-01
      ID: bl45p-ea-detector-02
  - service: bl45p-mo-panda-01
  - service: bl45p-mo-panda-02
  - service: bl45p-mo-brick-01
