project: bl45p
destination:
  name: pollux
  namespace: bl45p
source:
  repoURL: https://github.com/epics-containers/bl45p.git
  targetRevision: main

services:
  # shared epics services ######################################################
  - service: epics-pvcs
  - service: epics-opis

  # daq services ###############################################################
  - service: daq-rabbitmq
  - service: daq-blueapi
    enabled: false # --- boot looping

  # epics iocs #################################################################
  - service: bl45p-ea-dcam-01
    enabled: false # --- camera is offline
  - service: bl45p-ea-dcam-02
  - service: bl45p-mo-panda-01
  - service: bl45p-mo-panda-02
  - service: bl45p-mo-brick-01

  # other services #############################################################
