project: bl45p
destination:
  name: pollux
  namespace: bl45p
source:
  repoURL: https://github.com/epics-containers/bl45p.git
  targetRevision: main

# list of services to deploy from the /services folder of this repo
# each item is of the form:
# - service: service folder (name of service is the folder name)
#   enabled: set to false to turn off an IOC
#   targetRevision: optional override for targetRevision above
#   repoURL: optional override for repoURL above

services:
  # shared epics services ######################################################
  - service: epics-pvcs
  - service: epics-opis

  # daq services ###############################################################
  - service: daq-rabbitmq
  - service: daq-blueapi
    enabled: false # --- boot looping

  # epics iocs #################################################################
  - service: bl45p-ea-dcam-01
    enabled: false # --- camera is offline
  - service: bl45p-ea-dcam-02
  - service: bl45p-mo-panda-01
  - service: bl45p-mo-panda-02
  - service: bl45p-mo-brick-01
