{{ include "ioc-chart.ioc" . }}

{{- /*
  add the contents of every file in the config folder of this IOC helm chart
  into the config map - this must include start.sh the startup script.
  The files must be text only. Any files ending in .tz are explicitly ommitted
*/ -}}
---
# Create a new config map for every Deployment that containes the files
# found in config folder
apiVersion: v1
kind: ConfigMap
metadata:
  name: special-config
data:
  {{- range $path, $_ :=  .Files.Glob  "config/**/*.sh" }}
  {{ $path | trimPrefix "config/" }}: |-
{{ $.Files.Get $path | indent 4 }}
  {{ end }}