name: Build and publish a beamline's ioc helm charts

on:
  push:
  pull_request:

env:
  REGISTRY_ROOT: ghcr.io/epics-containers
  REGISTRY_FOLDER: ${{ github.event.repository.name }}
  CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CR_USER: USERNAME
  TAG: ${{ github.ref_name }}

  DO_PUSH: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags') }}

jobs:
  helm-build-push:
    runs-on: ubuntu-latest
    container:
      image: alpine/k8s:1.25.6
    steps:
      - uses: actions/checkout@v3
      - run: sh ./ci_build.sh
