name: Build and publish a beamline's ioc helm charts

on:
  push:
  pull_request:

env:
  HELM_VERSION_TO_INSTALL: 3.8.2 # version of HELM to install
  GHCR_ROOT: ghcr.io/epics-containers
  CR_PAT: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-and-push-helm-charts:
    name: publish helm charts to ghcr.io
    runs-on: ubuntu-latest
    environment: prod
    # TODO build of helm charts will in future use ibek. For now they are
    # hand coded. (Note that this workflow must continue to support pre-coded
    # charts for those who choose not use ibek).
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: install helm
        uses: Azure/setup-helm@v1
        with:
          version: ${{ env.HELM_VERSION_TO_INSTALL }}

      - name: push each ioc helm chart
        run: |
          pip install ibek >=0.9.1

          # tar up any config folders that require it
          ./tar_config_src.sh

          # helm tags must be SemVar. Use 0.0.1-b0 for testing the latest non-tagged build
          if [ "${GITHUB_REF_TYPE}" == "tag" ] ; then
            TAG=${GITHUB_REF_NAME}
          else
            TAG="0.0.1-b0"
          fi

          # make helm charts from ibek entity yaml files
          for ioc in $(ls *.yaml) ; do
            ibek build-helm "${ioc}"
          done

          # All IOCS that have changes since last pushed to the helm registry
          # will have version ${TAG} pushed 
          for ioc_root in $(ls -d iocs/*/) ; do
            ./helm-push.sh ${ioc_root} ${TAG}
          done
